---

CSR2:
    hostname: 10.10.21.121
    groups:
        - cisco_group

CSR1:
    hostname: 10.10.21.174
    groups:
        - cisco_group

vMX4:
    hostname: 10.10.21.121
    groups:
        - junos_group
    data:
        ospf_int_1: 'ge-0/0/3.0'
        ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.10.1/30'
            lo0:
                ipv4_address: '4.4.4.4/32'

vMX3:
    hostname: 10.10.21.174
    groups:
        - junos_group
    data:
        ospf_int_1: 'ge-0/0/3.0'
        ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.11.1/30'
            lo0:
                ipv4_address: '3.3.3.3/32'

vMX1:
    hostname: 10.10.21.69
    groups:
        - junos_group
    data:
        ospf_int_1: 'ge-0/0/3.0'
        ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.11.2/30'
            lo0:
                ipv4_address: '1.1.1.1/32'

vMX2:
    hostname: 10.10.21.15
    groups:
        - junos_group
    data:
        ospf_int_1: 'ge-0/0/3.0'
        ospf_area: '0.0.0.0'
        node_type: 'router'
        interfaces:
            ge-0/0/3:
                ipv4_address: '192.168.10.2/30'
            lo0:
                ipv4_address: '2.2.2.2/32'

vQFX1:
    hostname: 10.10.21.189
    groups:
        - junos_group
    data:
        node_type: 'switch'
        lacp: False

vQFX2:
    hostname: 10.10.21.49
    groups:
        - junos_group
    data:
        node_type: 'switch'
        lacp: True
        lacp_int_name:
            xe-0/0/1:
                isActive: True
            xe-0/0/2:
                isActive: True