---
inventory:
    plugin: YAMLInventory
    options:
        host_file: '/home/knox/Documents/CodeSamples/Python/Networking/Nornir/hosts/hosts.yml'
        group_file: '/home/knox/Documents/CodeSamples/Python/Networking/Nornir/groups/groups.yml'
        defaults_file: '/home/knox/Documents/CodeSamples/Python/Networking/Nornir/defaults/defaults.yml'

runner:
    plugin: threaded
    options:
        num_workers: 10