---
- name: Gather IOS-XE Facts
  hosts: 172.16.1.25
  connection: local
  tasks:
    - name: Gather IOS Facts
      ios_facts:
        provider:
          host: 172.16.1.25
          port: 22
          authorize: yes
          auth_pass: cisco
          username: cisco
          password: cisco

    - name: What is the IOS OS ver?
      debug:
        var: ansible_net_version

    - name: What is the hostname?
      debug:
        var: ansible_net_hostname
